name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"
      - name: Build
        run: |
          poetry install
          poetry build
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: output
          path: output

  run-unit-tests:
    name: test-unit
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]
        poetry-version: ["1.1.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: run tests
        run: |
          poetry install
          poetry run pytest --junitxml=test-results/results.xml --cov=./ --cov-report=xml tests
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: unit tests test-results
          path: test-results
